// packages/vibelab/vibelab-0.0.7.tar.gz/vibelab-0.0.7/web/src/components/ui/Button.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '../../lib/cn'

const buttonVariants = cva(
  // Base styles with interaction states
  [
    'inline-flex items-center justify-center font-medium',
    'transition-all duration-150',
    'focus-ring',
    'disabled:opacity-50 disabled:pointer-events-none disabled:cursor-not-allowed',
    // Active/pressed state - scale down slightly
    'active:scale-[0.97]',
  ].join(' '),
  {
    variants: {
      variant: {
        primary: [
          'bg-accent text-on-accent',
          'hover:bg-accent-hover hover:shadow-md hover:shadow-accent/20',
          'active:bg-accent active:shadow-sm',
        ].join(' '),
        secondary: [
          'bg-surface-2 text-text-primary border border-border',
          'hover:bg-surface-3 hover:border-text-tertiary hover:shadow-sm',
          'active:bg-surface active:shadow-none',
        ].join(' '),
        ghost: [
          'text-text-secondary',
          'hover:text-text-primary hover:bg-surface-3',
          'active:bg-surface-2',
        ].join(' '),
        danger: [
          'bg-status-error text-white',
          'hover:bg-red-600 hover:shadow-md hover:shadow-status-error/20',
          'active:bg-red-700 active:shadow-sm',
        ].join(' '),
        success: [
          'bg-status-success text-white',
          'hover:bg-green-600 hover:shadow-md hover:shadow-status-success/20',
          'active:bg-green-700 active:shadow-sm',
        ].join(' '),
        link: [
          'text-accent underline-offset-4',
          'hover:text-accent-hover hover:underline',
          'active:text-accent',
        ].join(' '),
      },
      size: {
        sm: 'h-7 px-2.5 text-xs rounded-sm gap-1',
        md: 'h-8 px-3 text-sm rounded gap-1.5',
        lg: 'h-9 px-4 text-sm rounded gap-2',
      },
    },
    defaultVariants: {
      variant: 'primary',
      size: 'md',
    },
  }
)

export interface ButtonProps
  extends ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => {
    return (
      <button
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)

Button.displayName = 'Button'

// packages/quick-pp/quick_pp-0.2.106.tar.gz/quick_pp-0.2.106/quick_pp/app/frontend/src/lib/components/ui/button/button.svelte
<script lang="ts" module>
	import { cn, type WithElementRef } from "$lib/utils.js";
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from "svelte/elements";
	import { type VariantProps, tv } from "tailwind-variants";

	export const buttonVariants = tv({
		base: "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium outline-none transition-all focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
		variants: {
			variant: {
				default: "bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",
				destructive:
					"bg-destructive shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white",
				outline:
					"bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border",
				secondary: "bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",
				ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
				link: "text-primary underline-offset-4 hover:underline",
			},
			size: {
				default: "h-9 px-4 py-2 has-[>svg]:px-3",
				sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
				lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
				icon: "size-9",
				"icon-sm": "size-8",
				"icon-lg": "size-10",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	});

	export type ButtonVariant = VariantProps<typeof buttonVariants>["variant"];
	export type ButtonSize = VariantProps<typeof buttonVariants>["size"];

	export type ButtonProps = WithElementRef<HTMLButtonAttributes> &
		WithElementRef<HTMLAnchorAttributes> & {
			variant?: ButtonVariant;
			size?: ButtonSize;
		};
</script>

<script lang="ts">
	let {
		class: className,
		variant = "default",
		size = "default",
		ref = $bindable(null),
		href = undefined,
		type = "button",
		disabled,
		children,
		...restProps
	}: ButtonProps = $props();
</script>

{#if href}
	<a
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		href={disabled ? undefined : href}
		aria-disabled={disabled}
		role={disabled ? "link" : undefined}
		tabindex={disabled ? -1 : undefined}
		{...restProps}
	>
		{@render children?.()}
	</a>
{:else}
	<button
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		{type}
		{disabled}
		{...restProps}
	>
		{@render children?.()}
	</button>
{/if}
